
namespace KSoft.Phoenix.Phx
{
	public enum BDifficultyType
	{
		EASY,
		NORMAL,
		HARD,
		LEGENDARY,

		K_NUMBER_OF_STANDARD_TYPES,

		CUSTOM = K_NUMBER_OF_STANDARD_TYPES,
		AUTOMATIC,

		K_NUMBER_OF
	};

	public enum BDifficultyTypeModifier
	{
		EASY,
		NORMAL,
		HARD,
		LEGENDARY,
		DEFAULT,
		SPCAI_DEFAULT,

		K_NUMBER_OF
	};

	public enum BOperatorType
	{
		NOT_EQUAL_TO,
		LESS_THAN,
		LESS_THAN_OR_EQUAL_TO,
		EQUAL_TO,
		GREATER_THAN_OR_EQUAL_TO,
		GREATER_THAN,
	};

	public enum BMathOperatorType
	{
		ADD,
		SUBTRACT,
		MULTIPLY,
		DIVIDE,
		MODULUS,
	};

	public enum BActionStatus
	{
		NOT_DONE,
		DONE_SUCCESS,
		DONE_FAILURE,
	};

	public enum BlosType
	{
		LOS_DONT_CARE,
		LOS_NORMAL,
		LOS_FULL_VISIBLE,
	};

	public enum BListPosition
	{
		FIRST,
		LAST,
		RANDOM,
	};

	public enum BExposedAction
	{
		EXPOSED_ACTION0,
		EXPOSED_ACTION1,
		EXPOSED_ACTION2,
	};

	public enum BDataScalar
	{
		ACCURACY,
		WORK_RATE,
		DAMAGE,
		LOS,
		VELOCITY,
		WEAPON_RANGE,
		DAMAGE_TAKEN,
	};

	public enum BFlareType
	{
		LOOK,
		HELP,
		MEET,
		ATTACK,
	};

	public enum BBidType
	{
		INVALID,
		NONE,
		SQUAD,
		TECH,
		BUILDING,
		POWER,
	};
	public enum BBidState
	{
		INVALID,
		INACTIVE,
		WAITING,
		APPROVED,
	};

	public enum BEventType
	{
		INVALID,

		CONTROL_TILT,
		CONTROL_ZOOM,
		CONTROL_ROTATE,
		CONTROL_PAN,
		CONTROL_CIRCLE_SELECT,
		CONTROL_CIRCLE_MULTI_SELECT,
		CONTROL_CLEAR_ALL_SELECTIONS,
		CONTROL_MODIFIER_ACTION,
		CONTROL_MODIFIER_SPEED,
		CONTROL_RESET_CAMERA_SETTINGS,
		CONTROL_GOTO_RALLY,
		CONTROL_GOTO_BASE,
		CONTROL_GOTO_SCOUT,
		CONTROL_GOTO_NODE,
		CONTROL_GOTO_HERO,
		CONTROL_GOTO_ALERT,
		CONTROL_GOTO_SELECTED,
		CONTROL_GROUP_SELECT,
		CONTROL_GROUP_GOTO,
		CONTROL_GROUP_ASSIGN,
		CONTROL_GROUP_ADD_TO,
		CONTROL_SCREEN_SELECT_MILITARY,
		CONTROL_GLOBAL_SELECT,
		CONTROL_DOUBLE_CLICK_SELECT,
		CONTROL_FIND_CROWD_MILITARY,
		CONTROL_FIND_CROWD_VILLAGER,
		CONTROL_SET_RALLY_POINT,
		FLARE,
		FLARE_HELP,
		FLARE_MEET,
		FLARE_ATTACK,
		MENU_SHOW_COMMAND,
		MENU_CLOSE_COMMAND,
		MENU_NAV_COMMAND,
		MENU_COMMAND_HAS_FOCUS0,
		MENU_COMMAND_HAS_FOCUS1,
		MENU_COMMAND_HAS_FOCUS2,
		MENU_COMMAND_HAS_FOCUS3,
		MENU_COMMAND_HAS_FOCUS4,
		MENU_COMMAND_HAS_FOCUS5,
		MENU_COMMAND_HAS_FOCUS6,
		MENU_COMMAND_HAS_FOCUS7,
		MENU_COMMAND_HAS_FOCUS_N,
		MENU_COMMAND_CLICKMENU_N,
		MENU_COMMAND_IS_MENU_OPEN,
		MENU_COMMANND_IS_MENU_NOT_OPEN,
		MENU_SHOW_POWER,
		MENU_CLOSE_POWER,
		MENU_POWER_HAS_FOCUS_N,
		MENU_POWER_CLICKMENU_N,
		MENU_POWER_IS_MENU_OPEN,
		MENU_POWER_IS_MENU_NOT_OPEN,
		MENU_SHOW_SELECT_POWER,
		MENU_SHOW_ABILITY,
		MENU_SHOW_TRIBUTE,
		MENU_SHOW_OBJECTIVES,
		GAME_ENTITY_BUILT,
		GAME_ENTITY_KILLED,
		CHAT_SHOWN,
		CHAT_REMOVED,
		CHAT_COMPLETED,
		COMMAND_BOWL,
		COMMAND_ABILITY,
		COMMAND_UNPACK,
		COMMAND_DO_WORK,
		COMMAND_ATTACK,
		COMMAND_MOVE,
		COMMAND_TRAIN_SQUAD,
		COMMAND_TRAIN_SQUAD_CANCEL,
		COMMAND_RESEARCH,
		COMMAND_RESEARCH_CANCEL,
		COMMAND_BUILD_OTHER,
		COMMAND_RECYCLE,
		COMMAND_RECYCLE_CANCEL,
		CAMERA_LOOKING_AT,
		SELECT_UNITS,
		CINEMATIC_COMPLETED,
		FADE_COMPLETED,
		USED_POWER,
		TIMER1_SEC,
		CONTROL_CIRCLE_SELECT_FULLY_GROWN,
		POWER_ORBITAL_COMPLETE,
		GAME_ENTITY_RAMMED,
		GAME_ENTITY_JACKED,
		GAME_ENTITY_KILLED_BY_NON_PROJECTILE,
	};

	public enum BGameStatePredicate
	{
		INVALID,

		SQUADS_SELECTED,
		HAS_SQUADS,
		HAS_BUILDINGS,
		HAS_RESOURCES,
		HAS_TECH,
		GAME_TIME,
	};

	public enum BPlayerScope
	{
		INVALID = TypeExtensions.K_NONE,

		ANY,
		PLAYER,
		TEAM,
		ENEMY,
		GAIA,

		K_NUMBER_OF
	};

	public enum BVisualDisplayPriority
	{
		NORMAL = 1,
		COMBAT,
		HIGH,
	};

	public enum BRelationType
	{
		ANY,
		SELF,
		ALLY,
		ENEMY,
		NEUTRAL,

		INVALID,
	};
}