
namespace KSoft.Phoenix.HaloWars
{
	public enum BChatSpeaker
	{
		SERENA,
		FORGE,
		CUTTER,
		VOICE_OF_GOD,
		GENERIC_SOLDIERS,
		ARCADIAN_POLICE,
		CIVILIANS,
		ANDERS,
		RHINO_COMMANDER,
		SPARTAN1,
		SPARTAN2,
		SPARTAN_SNIPER,
		SPARTAN_ROCKE_LAUNCHER,

		COVENANT = ANDERS,
		ARBITER = RHINO_COMMANDER,

		ODST = SPARTAN_ROCKE_LAUNCHER+1+1 + 1,
	};
}