
namespace KSoft.Phoenix.HaloWars
{
	public enum BFlashableUiItem // aka FlashableItems
	{
		MINIMAP,
		CIRCLE_MENU0,
		CIRCLE_MENU1,
		CIRCLE_MENU2,
		CIRCLE_MENU3,
		CIRCLE_MENU4,
		CIRCLE_MENU5,
		CIRCLE_MENU6,
		CIRCLE_MENU7,
		CIRCLE_MENU_POP,
		CIRCLE_MENU_POWER,
		CIRCLE_MENU_SUPPLY,
		DPAD,
		DPAD_UP,
		DPAD_DOWN,
		DPAD_LEFT,
		DPAD_RIGHT,
		RESOURCE_PANEL,
		RESOURCE_PANEL_POP,
		RESOURCE_PANEL_POWER,
		RESOURCE_PANEL_SUPPLY,
	};
}