
using BVector = System.Numerics.Vector4;
using BEntityID = System.Int32;

namespace KSoft.Phoenix.Runtime
{
	sealed class BSimOrder
		: IO.IEndianStreamSerializable
	{
		const int C_MAXIMUM_WAYPOINTS_ = 0xC8;

		internal static readonly FreeListInfo KFreeListInfo = new FreeListInfo(CSaveMarker.SIM_ORDER)
		{
			MaxCount=0x4E20,
		};

		public BSimTarget Target { get; private set; } = new BSimTarget();
		public BVector[] waypoints;
		public BEntityID ownerId;
		public uint id, refCount;
		public float angle;
		public sbyte mode;
		public byte priority;
		public bool attackMove, overridePosition, overrideRange,
			autoGeneratedAttackMove;

		#region IEndianStreamSerializable Members
		public void Serialize(IO.EndianStream s)
		{
			s.Stream(this.Target);
			BSaveGame.StreamVectorArray(s, ref this.waypoints, C_MAXIMUM_WAYPOINTS_);
			s.Stream(ref this.ownerId);
			s.Stream(ref this.id); s.Stream(ref this.refCount);
			s.Stream(ref this.angle);
			s.Stream(ref this.mode);
			s.Stream(ref this.priority);
			s.Stream(ref this.attackMove); s.Stream(ref this.overridePosition); s.Stream(ref this.overrideRange);
			s.Stream(ref this.autoGeneratedAttackMove);
		}
		#endregion
	};
}
