
using BVector = System.Numerics.Vector4;
using BEntityID = System.Int32;

namespace KSoft.Phoenix.Runtime
{
	sealed class BSimOrder
		: IO.IEndianStreamSerializable
	{
		const int cMaximumWaypoints = 0xC8;

		internal static readonly FreeListInfo kFreeListInfo = new FreeListInfo(cSaveMarker.SimOrder)
		{
			MaxCount=0x4E20,
		};

		public BSimTarget Target { get; private set; } = new BSimTarget();
		public BVector[] Waypoints;
		public BEntityID OwnerID;
		public uint ID, RefCount;
		public float Angle;
		public sbyte Mode;
		public byte Priority;
		public bool AttackMove, OverridePosition, OverrideRange,
			AutoGeneratedAttackMove;

		#region IEndianStreamSerializable Members
		public void Serialize(IO.EndianStream s)
		{
			s.Stream(this.Target);
			BSaveGame.StreamVectorArray(s, ref this.Waypoints, cMaximumWaypoints);
			s.Stream(ref this.OwnerID);
			s.Stream(ref this.ID); s.Stream(ref this.RefCount);
			s.Stream(ref this.Angle);
			s.Stream(ref this.Mode);
			s.Stream(ref this.Priority);
			s.Stream(ref this.AttackMove); s.Stream(ref this.OverridePosition); s.Stream(ref this.OverrideRange);
			s.Stream(ref this.AutoGeneratedAttackMove);
		}
		#endregion
	};
}
