
namespace KSoft.Phoenix.Phx
{
	// CV = CombatValue
	// HP = Hit points
	// SP = Shield points
	// DPS = Damage per second

	public enum BaiSquadAnalysisComponent
	{
		INVALID,
		CV_LIGHT,
		CV_LIGHT_ARMORED,
		CV_MEDIUM,
		CV_MEDIUM_AIR,
		CV_HEAVY,
		CV_BUILDING,
		CV_TOTAL,
		HP_LIGHT,
		HP_LIGHT_ARMORED,
		HP_MEDIUM,
		HP_MEDIUM_AIR,
		HP_HEAVY,
		HP_BUILDING,
		HP_TOTAL,
		SP_LIGHT,
		SP_LIGHT_ARMORED,
		SP_MEDIUM,
		SP_MEDIUM_AIR,
		SP_HEAVY,
		SP_BUILDING,
		SP_TOTAL,
		DPS_LIGHT,
		DPS_LIGHT_ARMORED,
		DPS_MEDIUM,
		DPS_MEDIUM_AIR,
		DPS_HEAVY,
		DPS_BUILDING,
		DPS_TOTAL,
		CV_PERCENT_LIGHT,
		CV_PERCENT_LIGHT_ARMORED,
		CV_PERCENT_MEDIUM,
		CV_PERCENT_MEDIUM_AIR,
		CV_PERCENT_HEAVY,
		CV_PERCENT_BUILDING,
		CV_STARS_LIGHT,
		CV_STARS_LIGHT_ARMORED,
		CV_STARS_MEDIUM,
		CV_STARS_MEDIUM_AIR,
		CV_STARS_HEAVY,
		CV_STARS_BUILDING,
		CV_STARS_TOTAL,
	};
}