using System;

namespace KSoft.Granny3D
{
	public enum GrannyMemberType
	{
		END_MEMBER,

		INLINE_MEMBER,
		REFERENCE_MEMBER,
		REFERENCE_TO_ARRAY_MEMBER,
		ARRAY_OF_REFERENCES_MEMBER,
		VARIANT_REFERENCE_MEMBER,
		SWITCHABLE_TYPE_MEMBER,
		REFERENCE_TO_VARIANT_ARRAY_MEMBER,
		STRING_MEMBER,
		TRANSFORM_MEMBER,
		REAL32_MEMBER,
		INT8_MEMBER,
		U_INT8_MEMBER,
		BINORMAL_INT8_MEMBER,
		NORMAL_U_INT8_MEMBER,
		INT16_MEMBER,
		U_INT16_MEMBER,
		BINORMAL_INT16_MEMBER,
		NORMAL_U_INT16_MEMBER,
		INT32_MEMBER,
		U_INT32_MEMBER,

		BOOL32_MEMBER = INT32_MEMBER,
	};

	[Flags]
	public enum GrannyTransformFlags
	{
		HAS_POSITION = 1<<0,
		HAS_ORIENTATION = 1<<1,
		HAS_SCALE_SHEAR = 1<<2,
	};
	[Flags]
	public enum GrannyTransformFileFlags
	{
		RENORMALIZE_NORMALS = 1<<0,
		REORDER_TRIANGLE_INDICES = 1<<1,
	};

	public enum GrannyTextureType
	{
		COLOR_MAP_TEXTURE_TYPE,
		CUBE_MAP_TEXTURE_TYPE,
	};

	public enum GrannyTextureEncoding
	{
		USER_TEXTURE_ENCODING,
		RAW_TEXTURE_ENCODING,
		S3_TC_TEXTURE_ENCODING,
		BINK_TEXTURE_ENCODING,
	};

	public enum GrannyMaterialTextureType
	{
		UNKNOWN_TEXTURE_TYPE,
		AMBIENT_COLOR_TEXTURE,
		DIFFUSE_COLOR_TEXTURE,
		SPECULAR_COLOR_TEXTURE,
		SELF_ILLUMINATION_TEXTURE,
		OPACITY_TEXTURE,
		BUMP_HEIGHT_TEXTURE,
		REFLECTION_TEXTURE,
		REFRACTION_TEXTURE,
		DISPLACEMENT_TEXTURE,
	};

	[Flags]
	public enum GrannyTrackGroupFlags
	{
		ACCUMULATION_EXTRACTED = 1<<0,
		TRACK_GROUP_IS_SORTED = 1<<1,
		ACCUMULATION_IS_VDA = 1<<2,
	};

	public enum GrannyDeformationType
	{
		DEFORM_POSITION = 1,
		DEFORM_POSITION_NORMAL,
		DEFORM_POSITION_NORMAL_TANGENT,
		DEFORM_POSITION_NORMAL_TANGENT_BINORMAL,
	};

	public enum GrannyDeformerTailFlags
	{
		DONT_ALLOW_UNCOPIED_TAIL,
		ALLOW_UNCOPIED_TAIL,
	};
}
