
namespace KSoft.Phoenix.HaloWars
{
	public enum BUnitFlag
	{
		ATTACK_BLOCKED,
	};
	public enum BSquadFlag
	{
		ATTACK_BLOCKED,
	};

	public enum BCodeProtoObject
	{
		// Objects
		REVEALER,
		BLOCKER,
		AI_EYE_ICON,
		UNIT_START,
		RALLY_START,
		OBSTRUCTION,
		OBJECTIVE_ARROW,
		OBJECTIVE_LOC_ARROW,
		PHYSICS_THROWN_OBJECT,
		SKIRMISH_EMPTY_BASE_OBJECT,
		SCN07_SCARAB,
		// Squads
		SKIRMISH_SCARAB,
		COBRA,
		VAMPIRE,
		LEADER_POWER_CASTER,
		// Objects
		SPC_HERO_FORGE,
		SPC_HERO_FORGE_WARTHOG,
		SPC_HERO_ANDERS,
		SPC_HERO_SPARTAN_ROCKET,
		SPC_HERO_SPARTAN_MG,
		SPC_HERO_SPARTAN_SNIPER,
		SMALL_SNOW_MOUND,
		MEDIUM_SNOW_MOUND,
		LARGE_SNOW_MOUND,
		STUN,
		EMP,
		HOTDROP_PAD_BEAM,
	};

	public enum BCodeObjectType
	{
		BUILDING,
		BUILDING_SOCKET,
		TURRET_SOCKET,
		TURRET_BUILDING,
		SETTLEMENT,
		BASE,
		ICON,
		GATHERABLE,
		INFANTRY,
		TRANSPORTER,
		TRANSPORTABLE,
		FLOOD,
		COVER,
		LOS_OBSTRUCTABLE,
		OBJECTIVE_ARROW,
		CAMPAIGN_HERO,
		HERO,
		HERO_DEATH,
		HOT_DROP_PICKUP,
		TELEPORT_DROPOFF,
		TELEPORT_PICKUP,
		GROUND_VEHICLE,
		GARRISON,
		UNSC_SUPPLY_PAD,
		COV_SUPPLY_PAD,
		BASE_SHIELD,
		WALL_SHIELD,
		LEADER,
		COVENANT,
		UNSC,
		BLACK_BOX,
		SKULL,
		BIRTH_ON_TOP,
		CAN_CRYO,
		HOOK,
	};
}