
namespace KSoft.Phoenix.Phx
{
	public enum BuiControlType
	{
		STICK_LEFT_UP,	STICK_LEFT_DOWN,	STICK_LEFT_LEFT,	STICK_LEFT_RIGHT,
		STICK_RIGHT_UP,	STICK_RIGHT_DOWN,	STICK_RIGHT_LEFT,	STICK_RIGHT_RIGHT,
		DPAD_UP,			DPAD_DOWN,		DPAD_LEFT,		DPAD_RIGHT,
		
		BUTTON_A,
		BUTTON_B,
		BUTTON_X,
		BUTTON_Y,
		BUTTON_START,
		BUTTON_BACK,
		BUTTON_SHOULDER_RIGHT,
		BUTTON_SHOULDER_LEFT,
		BUTTON_THUMB_LEFT,
		BUTTON_THUMB_RIGHT,
		TRIGGER_LEFT,
		TRIGGER_RIGHT,
		STICK_LEFT,
		STICK_RIGHT,
		DPAD,
		TRIGGERS,
		GAMEPAD_INSERT,
		GAMEPAD_REMOVE,
		
		KEY_BACK_SPACE,	KEY_TAB,		KEY_ENTER,		KEY_SHIFT,	KEY_CTRL,	KEY_ALT,		KEY_PAUSE,
		KEY_ESCAPE,		KEY_SPACE,	KEY_PAGE_UP,		KEY_PAGE_DOWN,KEY_END,		KEY_HOME,	KEY_LEFT,
		KEY_UP,			KEY_RIGHT,	KEY_DOWN,		KEY_PRT_SC,	KEY_INSERT,	KEY_DELETE,	KEY0,
		KEY1,			KEY2,		KEY3,			KEY4,		KEY5,		KEY6,		KEY7,
		KEY8,			KEY9,		KEY_A,			KEY_B,		KEY_C,		KEY_D,		KEY_E,
		KEY_F,			KEY_G,		KEY_H,			KEY_I,		KEY_J,		KEY_K,		KEY_L,
		KEY_M,			KEY_N,		KEY_O,			KEY_P,		KEY_Q,		KEY_R,		KEY_S,
		KEY_T,			KEY_U,		KEY_V,			KEY_W,		KEY_X,		KEY_Y,		KEY_Z,
		KEY_ACCENT,		KEY_ADD,		KEY_SEPARATOR,	KEY_DECIMAL,	KEY_DIVIDE,	KEY_F1,		KEY_F2,	
		KEY_F3,			KEY_F4,		KEY_F5,			KEY_F6,		KEY_F7,		KEY_F8,		KEY_F9,
		KEY_F10,			KEY_F11,		KEY_F12,			KEY_F16,

		KEY_SHIFT_LEFT,	KEY_SHIFT_RIGHT,	KEY_CTRL_LEFT,		KEY_CTRL_RIGHT,
		KEY_ALLT_LEFT,	KEY_ALT_RIGHT,	KEY_GREEN_MODIFIER,	KEY_ORANGE_MODIFIER,
	};
}