
namespace KSoft.Phoenix.Phx
{
	public enum BObjectDataType
	{
		INVALID = TypeExtensions.K_NONE,

		#region 0x00
		ENABLE = 0,
		HITPOINTS,
		SHIELDPOINTS,
		AMMO_MAX,
		LOS,
		MAXIMUM_VELOCITY,
		MAXIMUM_RANGE,
		RESEARCH_POINTS,
		RESOURCE_TRICKLE_RATE,
		MAXIMUM_RESOURCE_TRICKLE_RATE,
		RATE_AMOUNT,
		RATE_MULTIPLIER,
		RESOURCE,
		PROJECTILE,
		DAMAGE,
		MIN_RANGE,
		#endregion
		#region 0x10
		AOE_RADIUS,
		AOE_PRIMARY_TARGET_FACTOR,
		AOE_DISTANCE_FACTOR,
		AOE_DAMAGE_FACTOR,
		ACCURACY,
		MOVING_ACCURACY,
		MAX_DEVIATION,
		MOVING_MAX_DEVIATION,
		DATA_ACCURACY_DISTANCE_FACTOR,
		ACCURACY_DEVIATION_FACTOR,
		MAX_VELOCITY_LEAD,
		WORK_RATE,
		BUILD_POINTS,
		COST,
		AUTO_CLOAK,
		MOVE_WHILE_CLOAKED,
		#endregion
		#region 0x20
		ATTACK_WHILE_CLOAKED,
		ACTION_ENABLE,
		COMMAND_ENABLE,
		BOUNTY_RESOURCE,
		TRIBUTE_COST,
		SHIELD_REGEN_RATE,
		SHIELD_REGEN_DELAY,
		DAMAGE_MODIFIER,
		POP_CAP,
		POP_MAX,
		UNIT_TRAIN_LIMIT,
		SQUAD_TRAIN_LIMIT,
		REPAIR_COST,
		REPAIR_TIME,
		POWER_RECHARGE_TIME,
		POWER_USE_LIMIT,
		#endregion
		#region 0x30
		LEVEL,
		BOUNTY,
		MAX_CONTAINED,
		MAX_DAMAGE_PER_RAM,
		REFLECT_DAMAGE_FACTOR,
		AIR_BURST_SPAN,
		ABILITY_DISABLED,
		DO_TRATE,
		DO_TDURATION,
		IMPACT_EFFECT,
		AMMO_REGEN_RATE,
		COMMAND_SELECTABLE,
		DISPLAY_NAME_ID,
		ICON,
		ALT_ICON,
		STASIS,
		#endregion
		#region 0x40
		TURRET_YAW_RATE,
		TURRET_PITCH_RATE,
		POWER_LEVEL,
		BOARD_TIME,
		ABILITY_RECOVER_TIME,
		TECH_LEVEL,
		HP_BAR,
		WEAPON_PHYSICS_MULTIPLIER,
		DEATH_SPAWN,







		#endregion
	};

	public enum BObjectDataIconType : int
	{
		INVALID = TypeExtensions.K_NONE,

		UNIT,
		BUILDING,
		MISC,
		TECH,
	};
}